MsgBox "You're Gay?. Are you really Gay?", 4+64, "Lie Detector"
MsgBox "Please Dont Lie! Are you Really Gay?", 3+48, "Lie"
MsgBox "LIED AGAIN! Your gay and a liar?", 3+16, "Alert!"
MsgBox "Unable to remove gayness", 1+64, "Critical Error"
MsgBox "Gayness activated", 2+16, "Alert"
MsgBox "Removing Gayness.....", 2+16, "Gayness Removal"
MsgBox "The Gayness Persists.....", 2+48, "Persestant Gay"
MsgBox "Please Wait, Calling the gay police. Do you want to Stop it", 4+64, "Gay Police"
MsgBox "Could not stop. Authorities Notified", 1+16, "Call made"
MsgBox "Your Computer is Hacked", 0+64, "Alert"
MsgBox "HAHA This was Prank Brah", 0+64, "Fooled You"